// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#include "../ui.h"

void ui_Screen0_screen_init(void)
{
ui_Screen0 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button01 = lv_btn_create(ui_Screen0);
lv_obj_set_width( ui_Button01, 100);
lv_obj_set_height( ui_Button01, 73);
lv_obj_set_x( ui_Button01, 5 );
lv_obj_set_y( ui_Button01, 5 );
lv_obj_add_flag( ui_Button01, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button01, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label01 = lv_label_create(ui_Button01);
lv_obj_set_width( ui_Label01, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label01, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label01, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label01,"Jacket\nSetpoints");
lv_obj_set_style_text_align(ui_Label01, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button02 = lv_btn_create(ui_Screen0);
lv_obj_set_width( ui_Button02, 100);
lv_obj_set_height( ui_Button02, 73);
lv_obj_set_x( ui_Button02, 110 );
lv_obj_set_y( ui_Button02, 5 );
lv_obj_add_flag( ui_Button02, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button02, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label02 = lv_label_create(ui_Button02);
lv_obj_set_width( ui_Label02, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label02, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label02, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label02,"Temp\nSensors");
lv_obj_set_style_text_align(ui_Label02, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button03 = lv_btn_create(ui_Screen0);
lv_obj_set_width( ui_Button03, 100);
lv_obj_set_height( ui_Button03, 73);
lv_obj_set_x( ui_Button03, 215 );
lv_obj_set_y( ui_Button03, 5 );
lv_obj_add_flag( ui_Button03, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button03, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label03 = lv_label_create(ui_Button03);
lv_obj_set_width( ui_Label03, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label03, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label03, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label03,"Network\nStatus");
lv_obj_set_style_text_align(ui_Label03, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button04 = lv_btn_create(ui_Screen0);
lv_obj_set_width( ui_Button04, 100);
lv_obj_set_height( ui_Button04, 73);
lv_obj_set_x( ui_Button04, 5 );
lv_obj_set_y( ui_Button04, 83 );
lv_obj_add_flag( ui_Button04, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button04, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label04 = lv_label_create(ui_Button04);
lv_obj_set_width( ui_Label04, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label04, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label04, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label04,"Pump PID\nTuning");
lv_obj_set_style_text_align(ui_Label04, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button05 = lv_btn_create(ui_Screen0);
lv_obj_set_width( ui_Button05, 100);
lv_obj_set_height( ui_Button05, 73);
lv_obj_set_x( ui_Button05, 110 );
lv_obj_set_y( ui_Button05, 83 );
lv_obj_add_flag( ui_Button05, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button05, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label05 = lv_label_create(ui_Button05);
lv_obj_set_width( ui_Label05, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label05, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label05, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label05,"Log\nConsole");
lv_obj_set_style_text_align(ui_Label05, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button06 = lv_btn_create(ui_Screen0);
lv_obj_set_width( ui_Button06, 100);
lv_obj_set_height( ui_Button06, 73);
lv_obj_set_x( ui_Button06, 215 );
lv_obj_set_y( ui_Button06, 84 );
lv_obj_add_flag( ui_Button06, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button06, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label06 = lv_label_create(ui_Button06);
lv_obj_set_width( ui_Label06, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label06, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label06, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label06,"Screen 6");

ui_Button07 = lv_btn_create(ui_Screen0);
lv_obj_set_width( ui_Button07, 100);
lv_obj_set_height( ui_Button07, 73);
lv_obj_set_x( ui_Button07, 5 );
lv_obj_set_y( ui_Button07, 161 );
lv_obj_add_flag( ui_Button07, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button07, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label07 = lv_label_create(ui_Button07);
lv_obj_set_width( ui_Label07, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label07, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label07, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label07,"Screen 7");

ui_Button08 = lv_btn_create(ui_Screen0);
lv_obj_set_width( ui_Button08, 100);
lv_obj_set_height( ui_Button08, 73);
lv_obj_set_x( ui_Button08, 110 );
lv_obj_set_y( ui_Button08, 161 );
lv_obj_add_flag( ui_Button08, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button08, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label08 = lv_label_create(ui_Button08);
lv_obj_set_width( ui_Label08, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label08, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label08, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label08,"Screen 8");

ui_Button09 = lv_btn_create(ui_Screen0);
lv_obj_set_width( ui_Button09, 100);
lv_obj_set_height( ui_Button09, 73);
lv_obj_set_x( ui_Button09, 215 );
lv_obj_set_y( ui_Button09, 161 );
lv_obj_add_flag( ui_Button09, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button09, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label09 = lv_label_create(ui_Button09);
lv_obj_set_width( ui_Label09, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label09, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label09, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label09,"Screen 9");

ui_BackLabel00 = lv_label_create(ui_Screen0);
lv_obj_set_width( ui_BackLabel00, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackLabel00, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackLabel00, 0 );
lv_obj_set_y( ui_BackLabel00, -20 );
lv_label_set_text(ui_BackLabel00,"<");
lv_obj_set_style_text_color(ui_BackLabel00, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackLabel00, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackLabel00, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button01, ui_event_Button01, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button02, ui_event_Button02, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button03, ui_event_Button03, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button04, ui_event_Button04, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button05, ui_event_Button05, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button06, ui_event_Button06, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button07, ui_event_Button07, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button08, ui_event_Button08, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button09, ui_event_Button09, LV_EVENT_ALL, NULL);

}
