// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen4);
lv_img_set_src(ui_Image1, &ui_img_pid_widgets_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 0 );
lv_obj_set_y( ui_Image1, 25 );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header4 = lv_obj_create(ui_Screen4);
lv_obj_set_height( ui_Header4, 25);
lv_obj_set_width( ui_Header4, lv_pct(100));
lv_obj_set_align( ui_Header4, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Header4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header4, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackLabel04 = lv_label_create(ui_Header4);
lv_obj_set_width( ui_BackLabel04, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackLabel04, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackLabel04, 0 );
lv_obj_set_y( ui_BackLabel04, -20 );
lv_label_set_text(ui_BackLabel04,"<");
lv_obj_set_style_text_color(ui_BackLabel04, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackLabel04, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackLabel04, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Title4 = lv_label_create(ui_Header4);
lv_obj_set_width( ui_Header_Title4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Title4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Title4, 0 );
lv_obj_set_y( ui_Header_Title4, -9 );
lv_obj_set_align( ui_Header_Title4, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Header_Title4,"PID Tuning");
lv_obj_set_style_text_color(ui_Header_Title4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Title4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4_Ki_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Ki_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Ki_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Ki_val, -15 );
lv_obj_set_y( ui_Label4_Ki_val, 16 );
lv_obj_set_align( ui_Label4_Ki_val, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4_Ki_val,"--.-");

ui_Label4_Kp_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Kp_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Kp_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Kp_val, -15 );
lv_obj_set_y( ui_Label4_Kp_val, -42 );
lv_obj_set_align( ui_Label4_Kp_val, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4_Kp_val,"--.-");

ui_Label4_Kd_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Kd_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Kd_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Kd_val, -15 );
lv_obj_set_y( ui_Label4_Kd_val, 77 );
lv_obj_set_align( ui_Label4_Kd_val, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4_Kd_val,"--.-");

ui_Label4_Setpoint_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Setpoint_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Setpoint_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Setpoint_val, 8 );
lv_obj_set_y( ui_Label4_Setpoint_val, 110 );
lv_label_set_text(ui_Label4_Setpoint_val,"--.-");
lv_obj_set_style_text_color(ui_Label4_Setpoint_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4_Setpoint_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4_Error_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Error_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Error_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Error_val, 85 );
lv_obj_set_y( ui_Label4_Error_val, 120 );
lv_label_set_text(ui_Label4_Error_val,"--.-");
lv_obj_set_style_text_color(ui_Label4_Error_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4_Error_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4_Input_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Input_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Input_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Input_val, 8 );
lv_obj_set_y( ui_Label4_Input_val, 170 );
lv_label_set_text(ui_Label4_Input_val,"--.-");
lv_obj_set_style_text_color(ui_Label4_Input_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4_Input_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4_Iterm_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Iterm_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Iterm_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Iterm_val, 185 );
lv_obj_set_y( ui_Label4_Iterm_val, 120 );
lv_label_set_text(ui_Label4_Iterm_val,"--.-");
lv_obj_set_style_text_color(ui_Label4_Iterm_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4_Iterm_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4_Output_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Output_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Output_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Output_val, 265 );
lv_obj_set_y( ui_Label4_Output_val, 120 );
lv_label_set_text(ui_Label4_Output_val,"--.-");
lv_obj_set_style_text_color(ui_Label4_Output_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4_Output_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4_Pterm_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Pterm_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Pterm_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Pterm_val, 185 );
lv_obj_set_y( ui_Label4_Pterm_val, 60 );
lv_label_set_text(ui_Label4_Pterm_val,"--.-");
lv_obj_set_style_text_color(ui_Label4_Pterm_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4_Pterm_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4_Dterm_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4_Dterm_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4_Dterm_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4_Dterm_val, 185 );
lv_obj_set_y( ui_Label4_Dterm_val, 180 );
lv_label_set_text(ui_Label4_Dterm_val,"--.-");
lv_obj_set_style_text_color(ui_Label4_Dterm_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4_Dterm_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_Button4, 100);
lv_obj_set_height( ui_Button4, 80);
lv_obj_set_x( ui_Button4, 18 );
lv_obj_set_y( ui_Button4, 0 );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
