// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#include "../ui.h"

void ui_Screen9_screen_init(void)
{
ui_Screen9 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header9 = lv_obj_create(ui_Screen9);
lv_obj_set_height( ui_Header9, 25);
lv_obj_set_width( ui_Header9, lv_pct(100));
lv_obj_set_align( ui_Header9, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Header9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header9, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackLabel9 = lv_label_create(ui_Header9);
lv_obj_set_width( ui_BackLabel9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackLabel9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackLabel9, 0 );
lv_obj_set_y( ui_BackLabel9, -20 );
lv_label_set_text(ui_BackLabel9,"<");
lv_obj_set_style_text_color(ui_BackLabel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackLabel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackLabel9, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Title9 = lv_label_create(ui_Header9);
lv_obj_set_width( ui_Header_Title9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Title9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Title9, 0 );
lv_obj_set_y( ui_Header_Title9, -9 );
lv_obj_set_align( ui_Header_Title9, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Header_Title9,"Screen 9");
lv_obj_set_style_text_color(ui_Header_Title9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Title9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button9 = lv_btn_create(ui_Screen9);
lv_obj_set_width( ui_Button9, 100);
lv_obj_set_height( ui_Button9, 80);
lv_obj_add_flag( ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}
