// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header2 = lv_obj_create(ui_Screen2);
lv_obj_set_height( ui_Header2, 25);
lv_obj_set_width( ui_Header2, lv_pct(100));
lv_obj_set_align( ui_Header2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Header2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header2, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackLabel02 = lv_label_create(ui_Header2);
lv_obj_set_width( ui_BackLabel02, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackLabel02, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackLabel02, 0 );
lv_obj_set_y( ui_BackLabel02, -20 );
lv_label_set_text(ui_BackLabel02,"<");
lv_obj_set_style_text_color(ui_BackLabel02, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackLabel02, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackLabel02, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Title2 = lv_label_create(ui_Header2);
lv_obj_set_width( ui_Header_Title2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Title2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Title2, 0 );
lv_obj_set_y( ui_Header_Title2, -9 );
lv_obj_set_align( ui_Header_Title2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Header_Title2,"Temperature Sensors");
lv_label_set_recolor(ui_Header_Title2,"true");
lv_obj_set_style_text_color(ui_Header_Title2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Title2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2_sensor1 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel2_sensor1, 320);
lv_obj_set_height( ui_Panel2_sensor1, 25);
lv_obj_set_x( ui_Panel2_sensor1, 0 );
lv_obj_set_y( ui_Panel2_sensor1, 25 );
lv_obj_clear_flag( ui_Panel2_sensor1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2_sensor1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2_sensor1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2_sensor1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2_sensor1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar2_value1 = lv_bar_create(ui_Panel2_sensor1);
lv_bar_set_range(ui_Bar2_value1, -10,50);
lv_obj_set_width( ui_Bar2_value1, 95);
lv_obj_set_height( ui_Bar2_value1, 10);
lv_obj_set_x( ui_Bar2_value1, 60 );
lv_obj_set_y( ui_Bar2_value1, -7 );

ui_Label2_value1 = lv_label_create(ui_Panel2_sensor1);
lv_obj_set_width( ui_Label2_value1, 55);
lv_obj_set_height( ui_Label2_value1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2_value1, -5 );
lv_obj_set_y( ui_Label2_value1, -10 );
lv_label_set_long_mode(ui_Label2_value1,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_Label2_value1," --.-°C");
lv_obj_set_style_text_align(ui_Label2_value1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2_value1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2_name1 = lv_label_create(ui_Panel2_sensor1);
lv_obj_set_width( ui_Label2_name1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2_name1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2_name1, 165 );
lv_obj_set_y( ui_Label2_name1, -10 );
lv_label_set_text(ui_Label2_name1,"Compressor Inlet");

ui_Button2 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 80);
lv_obj_set_x( ui_Button2, -10 );
lv_obj_set_y( ui_Button2, -10 );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}
