// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: GasLid_SLS_Project

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_image = lv_img_create(ui_Screen4);
lv_img_set_src(ui_s4_image, &ui_img_pid_widgets_png);
lv_obj_set_width( ui_s4_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_image, 0 );
lv_obj_set_y( ui_s4_image, 25 );
lv_obj_add_flag( ui_s4_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_s4_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_s4_Header = lv_obj_create(ui_Screen4);
lv_obj_set_height( ui_s4_Header, 25);
lv_obj_set_width( ui_s4_Header, lv_pct(100));
lv_obj_set_align( ui_s4_Header, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_s4_Header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_s4_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_s4_Header, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_s4_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_s4_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_backLabel = lv_label_create(ui_s4_Header);
lv_obj_set_width( ui_s4_backLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_backLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_backLabel, 0 );
lv_obj_set_y( ui_s4_backLabel, -20 );
lv_label_set_text(ui_s4_backLabel,"<");
lv_obj_set_style_text_color(ui_s4_backLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_backLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_s4_backLabel, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_headerTitle = lv_label_create(ui_s4_Header);
lv_obj_set_width( ui_s4_headerTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_headerTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_headerTitle, 0 );
lv_obj_set_y( ui_s4_headerTitle, -9 );
lv_obj_set_align( ui_s4_headerTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_s4_headerTitle,"PID Tuning");
lv_obj_set_style_text_color(ui_s4_headerTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_headerTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_headerTime = lv_label_create(ui_s4_Header);
lv_obj_set_width( ui_s4_headerTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_headerTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_s4_headerTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_s4_headerTime,"--:--:--");
lv_obj_set_style_text_color(ui_s4_headerTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_headerTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_Ki_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Ki_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Ki_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Ki_val, -15 );
lv_obj_set_y( ui_s4_Ki_val, 16 );
lv_obj_set_align( ui_s4_Ki_val, LV_ALIGN_CENTER );
lv_label_set_text(ui_s4_Ki_val,"--.-");

ui_s4_Kp_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Kp_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Kp_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Kp_val, -15 );
lv_obj_set_y( ui_s4_Kp_val, -42 );
lv_obj_set_align( ui_s4_Kp_val, LV_ALIGN_CENTER );
lv_label_set_text(ui_s4_Kp_val,"--.-");

ui_s4_Kd_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Kd_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Kd_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Kd_val, -15 );
lv_obj_set_y( ui_s4_Kd_val, 77 );
lv_obj_set_align( ui_s4_Kd_val, LV_ALIGN_CENTER );
lv_label_set_text(ui_s4_Kd_val,"--.-");

ui_s4_Setpoint_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Setpoint_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Setpoint_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Setpoint_val, 8 );
lv_obj_set_y( ui_s4_Setpoint_val, 110 );
lv_label_set_text(ui_s4_Setpoint_val,"--.-");
lv_obj_set_style_text_color(ui_s4_Setpoint_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_Setpoint_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_Error_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Error_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Error_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Error_val, 85 );
lv_obj_set_y( ui_s4_Error_val, 120 );
lv_label_set_text(ui_s4_Error_val,"--.-");
lv_obj_set_style_text_color(ui_s4_Error_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_Error_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_Input_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Input_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Input_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Input_val, 8 );
lv_obj_set_y( ui_s4_Input_val, 170 );
lv_label_set_text(ui_s4_Input_val,"--.-");
lv_obj_set_style_text_color(ui_s4_Input_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_Input_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_Iterm_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Iterm_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Iterm_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Iterm_val, 185 );
lv_obj_set_y( ui_s4_Iterm_val, 120 );
lv_label_set_text(ui_s4_Iterm_val,"--.-");
lv_obj_set_style_text_color(ui_s4_Iterm_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_Iterm_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_Output_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Output_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Output_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Output_val, 265 );
lv_obj_set_y( ui_s4_Output_val, 120 );
lv_label_set_text(ui_s4_Output_val,"--.-");
lv_obj_set_style_text_color(ui_s4_Output_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_Output_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_Pterm_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Pterm_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Pterm_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Pterm_val, 185 );
lv_obj_set_y( ui_s4_Pterm_val, 60 );
lv_label_set_text(ui_s4_Pterm_val,"--.-");
lv_obj_set_style_text_color(ui_s4_Pterm_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_Pterm_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_Dterm_val = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_s4_Dterm_val, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s4_Dterm_val, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s4_Dterm_val, 185 );
lv_obj_set_y( ui_s4_Dterm_val, 180 );
lv_label_set_text(ui_s4_Dterm_val,"--.-");
lv_obj_set_style_text_color(ui_s4_Dterm_val, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s4_Dterm_val, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s4_backButton = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_s4_backButton, 100);
lv_obj_set_height( ui_s4_backButton, 80);
lv_obj_set_x( ui_s4_backButton, 18 );
lv_obj_set_y( ui_s4_backButton, 0 );
lv_obj_add_flag( ui_s4_backButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_s4_backButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_s4_backButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_s4_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_s4_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_s4_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_s4_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_s4_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_s4_backButton, ui_event_s4_backButton, LV_EVENT_ALL, NULL);

}
