// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: GasLid_SLS_Project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_s3_Header = lv_obj_create(ui_Screen3);
lv_obj_set_height( ui_s3_Header, 25);
lv_obj_set_width( ui_s3_Header, lv_pct(100));
lv_obj_set_align( ui_s3_Header, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_s3_Header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_s3_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_s3_Header, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_s3_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_s3_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s3_backLabel = lv_label_create(ui_s3_Header);
lv_obj_set_width( ui_s3_backLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_backLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_backLabel, 0 );
lv_obj_set_y( ui_s3_backLabel, -20 );
lv_label_set_text(ui_s3_backLabel,"<");
lv_obj_set_style_text_color(ui_s3_backLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s3_backLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_s3_backLabel, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s3_headerTitle = lv_label_create(ui_s3_Header);
lv_obj_set_width( ui_s3_headerTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_headerTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_headerTitle, 0 );
lv_obj_set_y( ui_s3_headerTitle, -9 );
lv_obj_set_align( ui_s3_headerTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_s3_headerTitle,"Notecard Info");
lv_obj_set_style_text_color(ui_s3_headerTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s3_headerTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s3_headerTime = lv_label_create(ui_s3_Header);
lv_obj_set_width( ui_s3_headerTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_headerTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_s3_headerTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_s3_headerTime,"--:--:--");
lv_obj_set_style_text_color(ui_s3_headerTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s3_headerTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s3_Bar1 = lv_bar_create(ui_Screen3);
lv_obj_set_width( ui_s3_Bar1, 10);
lv_obj_set_height( ui_s3_Bar1, 20);
lv_obj_set_x( ui_s3_Bar1, 100 );
lv_obj_set_y( ui_s3_Bar1, -160 );
lv_obj_set_align( ui_s3_Bar1, LV_ALIGN_BOTTOM_MID );

ui_s3_Bar2 = lv_bar_create(ui_Screen3);
lv_obj_set_width( ui_s3_Bar2, 10);
lv_obj_set_height( ui_s3_Bar2, 30);
lv_obj_set_x( ui_s3_Bar2, 115 );
lv_obj_set_y( ui_s3_Bar2, -160 );
lv_obj_set_align( ui_s3_Bar2, LV_ALIGN_BOTTOM_MID );

ui_s3_Bar3 = lv_bar_create(ui_Screen3);
lv_obj_set_width( ui_s3_Bar3, 10);
lv_obj_set_height( ui_s3_Bar3, 40);
lv_obj_set_x( ui_s3_Bar3, 130 );
lv_obj_set_y( ui_s3_Bar3, -160 );
lv_obj_set_align( ui_s3_Bar3, LV_ALIGN_BOTTOM_MID );

ui_s3_Bar4 = lv_bar_create(ui_Screen3);
lv_obj_set_width( ui_s3_Bar4, 10);
lv_obj_set_height( ui_s3_Bar4, 50);
lv_obj_set_x( ui_s3_Bar4, 145 );
lv_obj_set_y( ui_s3_Bar4, -160 );
lv_obj_set_align( ui_s3_Bar4, LV_ALIGN_BOTTOM_MID );

ui_s3_LabelRSSI = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_s3_LabelRSSI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_LabelRSSI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_LabelRSSI, 12 );
lv_obj_set_y( ui_s3_LabelRSSI, 35 );
lv_label_set_text(ui_s3_LabelRSSI,"RSSI: ----");

ui_s3_LabelConnected = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_s3_LabelConnected, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_LabelConnected, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_LabelConnected, 12 );
lv_obj_set_y( ui_s3_LabelConnected, 60 );
lv_label_set_text(ui_s3_LabelConnected,"Connected: ----");

ui_s3_LabelBand = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_s3_LabelBand, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_LabelBand, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_LabelBand, 135 );
lv_obj_set_y( ui_s3_LabelBand, 35 );
lv_label_set_text(ui_s3_LabelBand,"Band: ----");

ui_s3_LabelRat = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_s3_LabelRat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_LabelRat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_LabelRat, 135 );
lv_obj_set_y( ui_s3_LabelRat, 60 );
lv_label_set_text(ui_s3_LabelRat,"RAT: ----");

ui_s3_LabelSerial = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_s3_LabelSerial, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_LabelSerial, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_LabelSerial, 12 );
lv_obj_set_y( ui_s3_LabelSerial, 85 );
lv_label_set_text(ui_s3_LabelSerial,"SN: ----");

ui_s3_LabelSyncStatus = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_s3_LabelSyncStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_LabelSyncStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_LabelSyncStatus, 12 );
lv_obj_set_y( ui_s3_LabelSyncStatus, 185 );
lv_label_set_text(ui_s3_LabelSyncStatus,"Sync Status :");

ui_s3_LabelDevice = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_s3_LabelDevice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_LabelDevice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_LabelDevice, 12 );
lv_obj_set_y( ui_s3_LabelDevice, 110 );
lv_label_set_text(ui_s3_LabelDevice,"UID : ----");

ui_s3_LabelHubStatus = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_s3_LabelHubStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_LabelHubStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_LabelHubStatus, 12 );
lv_obj_set_y( ui_s3_LabelHubStatus, 135 );
lv_label_set_text(ui_s3_LabelHubStatus,"Hub Status :");

ui_s3_TextAreaHubStatus = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_s3_TextAreaHubStatus, 205);
lv_obj_set_height( ui_s3_TextAreaHubStatus, 52);
lv_obj_set_x( ui_s3_TextAreaHubStatus, 110 );
lv_obj_set_y( ui_s3_TextAreaHubStatus, 130 );
lv_textarea_set_placeholder_text(ui_s3_TextAreaHubStatus,"None");



ui_s3_TextAreaSyncStatus = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_s3_TextAreaSyncStatus, 205);
lv_obj_set_height( ui_s3_TextAreaSyncStatus, 52);
lv_obj_set_x( ui_s3_TextAreaSyncStatus, 110 );
lv_obj_set_y( ui_s3_TextAreaSyncStatus, 185 );
lv_textarea_set_placeholder_text(ui_s3_TextAreaSyncStatus,"None");



ui_s3_Button_Refresh = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_s3_Button_Refresh, 10);
lv_obj_set_height( ui_s3_Button_Refresh, 10);
lv_obj_set_x( ui_s3_Button_Refresh, 144 );
lv_obj_set_y( ui_s3_Button_Refresh, -25 );
lv_obj_set_align( ui_s3_Button_Refresh, LV_ALIGN_CENTER );
lv_obj_add_state( ui_s3_Button_Refresh, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_s3_Button_Refresh, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_s3_Button_Refresh, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_s3_Label_Refresh = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_s3_Label_Refresh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s3_Label_Refresh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s3_Label_Refresh, 107 );
lv_obj_set_y( ui_s3_Label_Refresh, -25 );
lv_obj_set_align( ui_s3_Label_Refresh, LV_ALIGN_CENTER );
lv_label_set_text(ui_s3_Label_Refresh,"Refresh");

ui_s3_backButton = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_s3_backButton, 100);
lv_obj_set_height( ui_s3_backButton, 80);
lv_obj_add_flag( ui_s3_backButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_s3_backButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_s3_backButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_s3_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_s3_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_s3_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_s3_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_s3_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_s3_backButton, ui_event_s3_backButton, LV_EVENT_ALL, NULL);

}
