// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: GasLid_SLS_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
ui_Screen5 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scrollbar_mode(ui_Screen5, LV_SCROLLBAR_MODE_OFF);

ui_s5_Header = lv_obj_create(ui_Screen5);
lv_obj_set_height( ui_s5_Header, 25);
lv_obj_set_width( ui_s5_Header, lv_pct(100));
lv_obj_set_align( ui_s5_Header, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_s5_Header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_s5_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_s5_Header, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_s5_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_s5_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s5_backLabel = lv_label_create(ui_s5_Header);
lv_obj_set_width( ui_s5_backLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s5_backLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s5_backLabel, 0 );
lv_obj_set_y( ui_s5_backLabel, -20 );
lv_label_set_text(ui_s5_backLabel,"<");
lv_obj_set_style_text_color(ui_s5_backLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s5_backLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_s5_backLabel, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s5_headerTitle = lv_label_create(ui_s5_Header);
lv_obj_set_width( ui_s5_headerTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s5_headerTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_s5_headerTitle, 0 );
lv_obj_set_y( ui_s5_headerTitle, -9 );
lv_obj_set_align( ui_s5_headerTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_s5_headerTitle,"Logs");
lv_obj_set_style_text_color(ui_s5_headerTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s5_headerTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s5_headerTime = lv_label_create(ui_s5_Header);
lv_obj_set_width( ui_s5_headerTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_s5_headerTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_s5_headerTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_s5_headerTime,"--:--:--");
lv_obj_set_style_text_color(ui_s5_headerTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_s5_headerTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_s5_TextAreaLog = lv_textarea_create(ui_Screen5);
lv_obj_set_width( ui_s5_TextAreaLog, 313);
lv_obj_set_height( ui_s5_TextAreaLog, 208);
lv_obj_set_x( ui_s5_TextAreaLog, 3 );
lv_obj_set_y( ui_s5_TextAreaLog, 28 );
lv_textarea_set_placeholder_text(ui_s5_TextAreaLog,"Placeholder...");
lv_obj_clear_flag( ui_s5_TextAreaLog, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags



ui_s5_backButton = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_s5_backButton, 100);
lv_obj_set_height( ui_s5_backButton, 80);
lv_obj_add_flag( ui_s5_backButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_s5_backButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_s5_backButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_s5_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_s5_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_s5_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_s5_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_s5_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_s5_backButton, ui_event_s5_backButton, LV_EVENT_ALL, NULL);

}
